apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress-service-name | default "example-pod-service"}}
  namespace: {{ .Values.default-ingress-namespace | default "web"}}
spec:
  selector:
    app: {{ .Values.examplePod | default "examplePod"}}  # Der Service selektiert Pods mit diesem Label
  ports:
    - protocol: TCP
      port: {{ .Values.examplePod-port | 80}}  # Der Port, auf dem der Service im Cluster erreichbar ist
      targetPort: 80  # Der Port im Pod, auf dem der echoserver läuft