apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress_service_name | default "examplepodservice" }}
  namespace: {{ .Values.default_ingress_namespace | default "web" }}
spec:
  selector:
    app: {{ .Values.examplePod | default "examplepod" }}  # Der Service selektiert Pods mit diesem Label
  ports:
    - protocol: TCP
      port: {{ .Values.examplePod_port | default 80 }}  # Der Port, auf dem der Service im Cluster erreichbar ist
      targetPort: 80  # Der Port im Pod, auf dem der echoserver läuft
