apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-server-ingress
  namespace: web
  annotations:
    haproxy-ingress.github.io/rewrite-target: /
spec:
  ingressClassName: haproxy
  rules:
    - host: {{ .Values.hostName | default "marex.labhome"}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingressServiceName | default "examplepodservice" }}
                port:
                  number: {{ .ValuesIngressPervicePort | default 80 }}
